/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wc;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
/**
 *
 * @author Pushkar
 */

public class Fan_CreateTeam extends javax.swing.JFrame {

    /**
     * Creates new form Fan_CreateTeam
     */
    static String user;
    static int cid;
    static int mid;
    static int sid;
    public Fan_CreateTeam(String abc,int a,int b,int c) {
        user=abc;
        mid=b;
        sid=c;
        initComponents();
    }
    String url="jdbc:oracle:thin:@DESKTOP-08UAP4B:1521:XE";
    String username="push";
    String password="umsy0410";
    int a,b,c,d=0;
    int total=10000;
    Vector temp = new Vector();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playersTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        goalkeeperTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        defenderTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        forwardTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        midfielderTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        playersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Players", "Position", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(playersTable);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel1.setText("Select Goalkeeper");

        jButton1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        goalkeeperTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Position", "Rating", "Country", "Cost"
            }
        ));
        jScrollPane2.setViewportView(goalkeeperTable);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setText("Select Defenders");

        defenderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Position", "Rating", "Country", "Cost"
            }
        ));
        jScrollPane3.setViewportView(defenderTable);

        jButton2.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextField1.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel3.setText("Enter Name");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel4.setText("Enter Name");

        jTextField2.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextField2.setText("jTextField2");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel5.setText("Select Midfielders");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel6.setText("Enter Name");

        jTextField3.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextField3.setText("jTextField3");

        jButton3.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel7.setText("Select Forwards");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jLabel8.setText("Enter Name");

        jTextField4.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextField4.setText("jTextField4");

        jButton4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        forwardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Position", "Rating", "Country", "Cost"
            }
        ));
        jScrollPane4.setViewportView(forwardTable);

        midfielderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Position", "Rating", "Country", "Cost"
            }
        ));
        jScrollPane5.setViewportView(midfielderTable);

        jButton5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextField5.setText("jTextField5");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel9.setText("Remove player ");

        jButton6.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(46, 46, 46)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(31, 31, 31)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton4)
                            .addComponent(jLabel7)
                            .addComponent(jButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel tb11=(DefaultTableModel)playersTable.getModel();
        DefaultTableModel tb13=(DefaultTableModel)defenderTable.getModel();
        DefaultTableModel tb12=(DefaultTableModel)goalkeeperTable.getModel();
        DefaultTableModel tb14=(DefaultTableModel)midfielderTable.getModel();
        DefaultTableModel tb15=(DefaultTableModel)forwardTable.getModel();
        String goalkeeper="select * from Player where positon='goalkeeper' and player_id not in (select player_id from Club_Player where cid="+ cid+")";
        String midfielder="select * from Player where positon like '%Midfielder%' and player_id not in (select player_id from Club_Player where cid="+ cid+")";
        String defender="select * from Player where positon like '%Defender%' and player_id not in (select player_id from Club_Player where cid="+ cid+")";
        String forward="select * from Player where positon like '%Forward%' or position like '%Striker%' and player_id not in (select player_id from Club_Player where cid="+ cid+")";
        String players="select name,positon,rating from Player,Club_Player where Player.player_id=Club_Player.player_id and Club_Player.cid="+cid;
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            ResultSet rs1=stmt1.executeQuery(players);
            tb11.setRowCount(0);
            while(rs1.next()){
                Object row1[]=new Object[2];
                row1[0]=rs1.getObject(1).toString();
                row1[1]=rs1.getObject(2).toString(); 
                row1[2]=rs1.getObject(3).toString(); 
                tb11.addRow(row1);
            }
            Statement stmt2=conn.createStatement();
            ResultSet rs2=stmt2.executeQuery(goalkeeper);
            tb12.setRowCount(0);
            while(rs2.next()){
                Object row2[]=new Object[5];
                row2[0]=rs2.getObject(1).toString();
                row2[1]=rs2.getObject(2).toString();
                row2[2]=rs2.getObject(3).toString();
                row2[3]=rs2.getObject(4).toString();
                row2[4]=rs2.getObject(5).toString();
                                
                tb12.addRow(row2);
            }
            Statement stmt3=conn.createStatement();
            ResultSet rs3=stmt3.executeQuery(defender);
            tb13.setRowCount(0);
            while(rs3.next()){
                Object row3[]=new Object[5];
                row3[0]=rs3.getObject(1).toString();
                row3[1]=rs3.getObject(2).toString();
                row3[2]=rs3.getObject(3).toString();
                row3[3]=rs3.getObject(4).toString();
                row3[4]=rs3.getObject(5).toString();
                                
                tb13.addRow(row3);
            }
            Statement stmt4=conn.createStatement();
            ResultSet rs4=stmt4.executeQuery(midfielder);
            tb14.setRowCount(0);
            while(rs3.next()){
                Object row4[]=new Object[5];
                row4[0]=rs4.getObject(1).toString();
                row4[1]=rs4.getObject(2).toString();
                row4[2]=rs4.getObject(3).toString();
                row4[3]=rs4.getObject(4).toString();
                row4[4]=rs4.getObject(5).toString();
                                
                tb14.addRow(row4);
            }
            Statement stmt5=conn.createStatement();
            ResultSet rs5=stmt5.executeQuery(forward);
            tb15.setRowCount(0);
            while(rs3.next()){
                Object row5[]=new Object[5];
                row5[0]=rs5.getObject(1).toString();
                row5[1]=rs5.getObject(2).toString();
                row5[2]=rs5.getObject(3).toString();
                row5[3]=rs5.getObject(4).toString();
                row5[4]=rs5.getObject(5).toString();
                                
                tb14.addRow(row5);
            }
            rs1.close();
            rs2.close();
            rs3.close();
            rs4.close();
            rs5.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }



    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String chosen=jTextField1.getText();
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt2=conn.createStatement();
            //a=stmt1.execute("select count(*) from Player,Club_Player where Player.player_id=Club_Player.player_id and position='goalkeeper' and cid="+cid+"");
            if(a>=1)
            {
                JOptionPane.showMessageDialog(this,"No more goalkeepers can be added!");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                Statement stmt4=conn.createStatement();
                ResultSet rs=stmt3.executeQuery("select player_id from Player where name='"+chosen+"'");
                int pid = ((Number)rs.getObject(0)).intValue();
                //get player cost........write here 
                if(total-cost<0)
                {
                    JOptionPane.showMessageDialog(this,"Money insufficient");
                }
                else{
                temp.add(pid);
                a++;
                }//stmt4.executeQuery("insert into Club_Player values("+cid+","+pid+")");
            }
                
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ((a+b+c+d)<11)
        {
            if(a<1)
                JOptionPane.showMessageDialog(this,"Please add 1 goalkeeper");
            if(b<4)
                JOptionPane.showMessageDialog(this,"please add more defenders");
            if(c<3)
                JOptionPane.showMessageDialog(this,"please add more midfielders");
            if(d<3)
                JOptionPane.showMessageDialog(this,"please add more attackers");
        }
        else{
        try{
            //Now you have vector temp ready with 11 players.
            //travese the vector and add the values to club_players.
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt2=conn.createStatement();
            Statement stmt3=conn.createStatement();
            Statement stmt4=conn.createStatement();
            Statement stmt5=conn.createStatement();
            Statement stmt6=conn.createStatement();
            Statement stmt7=conn.createStatement();
            Statement stmt8=conn.createStatement();
            stmt1.executeQuery("insert into User_Club values('"+user+"',"+cid+")");
            stmt2.executeQuery("update Club set flag=1 where Club_ID="+cid);
            stmt3.executeQuery("insert into Club_Manager values("+cid+","+mid+")");
            stmt4.executeQuery("insert into Club_Stadium values("+cid+","+sid+")");
            ResultSet rs1=stmt5.executeQuery("select Club_Name from Club where Club_ID="+cid);
            String club_name=rs1.getObject(1).toString();
            ResultSet rs2=stmt6.executeQuery("select manager_name from manager where manager_id="+mid);
            String manager_name=rs2.getObject(1).toString();
            ResultSet rs3=stmt7.executeQuery("select stadium_name from stadium where stadium_id="+sid);
            String stadium_name=rs3.getObject(1).toString();
            stmt8.executeQuery("insert into League values('"+club_name+"','"+manager_name+"','"+stadium_name+"')");
            
            
            
                
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String chosen=jTextField1.getText();
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt2=conn.createStatement();
            //a=stmt1.execute("select count(*) from Player,Club_Player where Player.player_id=Club_Player.player_id and position='goalkeeper' and cid="+cid+"");
            if(b>=4)
            {
                JOptionPane.showMessageDialog(this,"No more than 4 defenders can be added!");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                Statement stmt4=conn.createStatement();
                ResultSet rs=stmt3.executeQuery("select player_id from Player where name='"+chosen+"'");
                int pid = ((Number)rs.getObject(0)).intValue();
                //get player cost........write here 
                if(total-cost<0)
                {
                    JOptionPane.showMessageDialog(this,"Money insufficient");
                }
                else{
                total=total-cost;
                temp.add(pid);
                a++;
                }
            }
                
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          String chosen=jTextField3.getText();
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt2=conn.createStatement();
            //a=stmt1.execute("select count(*) from Player,Club_Player where Player.player_id=Club_Player.player_id and position='goalkeeper' and cid="+cid+"");
            if(c>=3)
            {
                JOptionPane.showMessageDialog(this,"No more than 3 midfielders can be added!");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                Statement stmt4=conn.createStatement();
                ResultSet rs=stmt3.executeQuery("select player_id from Player where name='"+chosen+"'");
                int pid = ((Number)rs.getObject(0)).intValue();
                //get player cost........write here 
                if(total-cost<0)
                {
                    JOptionPane.showMessageDialog(this,"Money insufficient");
                }
                else{
                total=total-cost;
                temp.add(pid);
                a++;
                }
            }
                
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          String chosen=jTextField4.getText();
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt1=conn.createStatement();
            Statement stmt2=conn.createStatement();
            //a=stmt1.execute("select count(*) from Player,Club_Player where Player.player_id=Club_Player.player_id and position='goalkeeper' and cid="+cid+"");
            if(b>=4)
            {
                JOptionPane.showMessageDialog(this,"No more than 3 forwards can be added!");
            }
            else
            {
                Statement stmt3=conn.createStatement();
                Statement stmt4=conn.createStatement();
                ResultSet rs=stmt3.executeQuery("select player_id from Player where name='"+chosen+"'");
                int pid = ((Number)rs.getObject(0)).intValue();
                //get player cost........write here 
                if(total-cost<0)
                {
                    JOptionPane.showMessageDialog(this,"Money insufficient");
                }
                else{
                total=total-cost;
                temp.add(pid);
                a++;
                }
            }
                
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String chosen=jTextField5.getText();
        //pid of that player in int pid;
        //get position in String pos;
        //get int cost;
        if(pos.equals("goalkeeper"))
        {
            total=total+cost;
            a--;
            temp.remove((Integer)pid); 
        }
        else if(pos.equals("defender"))
        {
            total=total+cost;
            b--;
            temp.remove((Integer)pid); 
        }
        else if(pos.equals("midfielder"))
        {
            total=total+cost;
            c--;
            temp.remove((Integer)pid); 
        }
        else
        {
            total=total+cost;
            d--;
            temp.remove((Integer)pid); 
        }
        //populate with new values
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fan_CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fan_CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fan_CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fan_CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fan_CreateTeam(user,cid,mid,sid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable defenderTable;
    private javax.swing.JTable forwardTable;
    private javax.swing.JTable goalkeeperTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable midfielderTable;
    private javax.swing.JTable playersTable;
    // End of variables declaration//GEN-END:variables
}
